### ISSUE TITLE
Ensure integration with maintenance norms

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/dlss-capistrano-docker#4]
- [x] Grant @sul-dlss/infrastructure-team admin access to GitHub repo
- [x] Add to [access-update-scripts](https://github.com/sul-dlss/access-update-scripts/blob/master/infrastructure/projects.yml)
- [x] Once gem is published, [grant ownership to sul-devops-team](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/releasing_gems.md#adding-the-dlss-service-account-to-new-gems)
- [x] Add circle for linting

**Comment by ndushay** [comment]
- [ ] tag infrastructure and gem and whatever else applies
